### ISSUE TITLE
[1.0.11-1.19.2-Forge] Exception deserializing stack

### ISSUE THREAD

**Issue by BookerCatch** [emilyploszaj/emi#257]
I have a json file formatted to hide a single enchanted book. The book is hidden, but there is an error printed in the log. See attached snippet.

[latest.log](https://github.com/emilyploszaj/emi/files/12139724/latest.log)

**Comment by Disketaa** [comment]
+1

![image](https://github.com/emilyploszaj/emi/assets/76956762/caa319e9-665a-4595-8f65-48fa3a36efec)

**Comment by MrGreenTea** [comment]
I've had the same happen for things like the creative items from create and many more with all this error:

```
java.lang.NullPointerException: Cannot invoke "dev.emi.emi.api.stack.serializer.EmiIngredientSerializer.deserialize(com.google.gson.JsonElement)" because the return value of "java.util.Map.get(Object)" is null`
```

My first assumption is that it might have something to do with the fact that these items are uncraftable?

<details><summary>Some of the mods this happens with</summary>
<p>


### Vanilla
- `Exception deserializing stack "fluid:minecraft:water"`

### Create
- `Exception deserializing stack "item:create:handheld_worldshaper"`
- `Exception deserializing stack "item:create:creative_motor"`
- `Exception deserializing stack "item:create:creative_fluid_tank"`
- `Exception deserializing stack "item:create:creative_crate"`
- `Exception deserializing stack "item:create:creative_blaze_cake"`

### Delightful Creators
- `Exception deserializing stack "fluid:delightfulcreators:beetroot_soup"`
- `Exception deserializing stack "item:delightfulcreators:beetroot_soup_bucket"`

### Farmer's Delight
- `Exception deserializing stack "item:farmersdelight:cake_slice"`
- `Exception deserializing stack "item:farmersdelight:pumpkin_slice"`

any all other pie/cake slices

### End Remastered
- `Exception deserializing stack "item:endrem:black_eye"`

and all other uncraftable eyes

</p>
</details>

**Comment by SiverDX** [comment]
Since I'm hiding a lot of enchanted books I get around 100k lines of this per world join
I'm already using Log Begone to hide them but it still kills the Prism Launcher Logger since that one seems to bypass that mod

**Comment by emilyploszaj** [comment]
This is something I want to be fixing for the next release

**Comment by emilyploszaj** [comment]
Fixed in 1.0.24

**Comment by Disketaa** [comment]
1.20.2, still getting
[latest.log](https://github.com/emilyploszaj/emi/files/13333190/latest.log)
