### ISSUE TITLE
[1.20.1-Forge] EMI not properly showing up. Stuck at "Baking Recipes". (JEI is installed.)

### ISSUE THREAD

**Issue by Gbergz** [emilyploszaj/emi#259]
# What happened:
Since 1.0.13 update and above EMI is stuck at "Experiencing delay, is everything alright?. Baking Recipes. EMI Reloading..."
(JEI is installed.)
![bild](https://github.com/emilyploszaj/emi/assets/26634554/976dbf4f-4103-40ff-b488-3f7a7fd014b1)

Versions 1.0.12 and below work fine. No longer stuck / experiencing delays.

# **Versions:**
**MC:** 1.20.1
**Forge:** 47.1.3
**EMI:** from 1.0.13 & 1.0.14 and up.
**JEI:** 15.2.0.23

# Logs:
If needed: https://gist.githubusercontent.com/Gbergz/9b3dc2ceb0102b7960e02ac9f2cff330/raw/d5140048ebd2716f8096678be46b0113e8fc9efa/gistfile1.txt

**Comment by emilyploszaj** [comment]
Based on the log ending on baking the index, this was fixed with the latest update, 1.0.15

**Comment by AndreAugustoDev** [comment]
I still have this problem in the latest version for 1.19.2
MC: 1.19.2
Forge: 43.2.21
EMI: 1.0.15
After a few minutes it loads
[latest.log](https://mclo.gs/w2H5gsE)
[debug.log](https://mclo.gs/jI259V6)

**Comment by emilyploszaj** [comment]
I originally closed this too early conflating it with another issue. After further testing I was able to discover the problem and resolve it properly in 1.0.16
