### ISSUE TITLE
Black screen in Integrated Terminals

### ISSUE THREAD

**Issue by PTALTS-LK** [emilyploszaj/emi#571]
When I enable the filtering feature (By double-clicking on the search box) of the search box, the whole screen turns black
![image](https://github.com/emilyploszaj/emi/assets/62936489/0179cc69-bfae-4536-a52c-94e2634e1d1d)
![image](https://github.com/emilyploszaj/emi/assets/62936489/8564e8d6-f456-45ee-9193-ff5ed64d9362)

**Comment by emilyploszaj** [comment]
If this is related to the issue I believe it is, this should be resolved in 1.1.11

**Comment by Vaelzan** [comment]
> If this is related to the issue I believe it is, this should be resolved in 1.1.11

I just checked with 1.1.12 and it's still present, unfortunately.

Edit: Tooltips are also rendered behind the EMI sidebar items while in that same screen in Integrated Terminals. Not sure if this needs to be dealt with on EMI's end or Integrated Terminals.
