### ISSUE TITLE
Log Spam with JEI

### ISSUE THREAD

**Issue by LunarFactory** [emilyploszaj/emi#653]
here's my spamming log-

```
java.lang.AbstractMethodError: Receiver class dev.emi.emi.jemi.impl.JemiRecipeSlotBuilder does not define or inherit an implementation of the resolved method 'mezz.jei.api.gui.builder.IIngredientAcceptor addTypedIngredients(java.util.List)' of interface mezz.jei.api.gui.builder.IRecipeSlotBuilder.
01:22:30.056
game
at TRANSFORMER/jei@15.10.0.35/mezz.jei.library.plugins.jei.tags.TagInfoRecipeCategory.setRecipe(TagInfoRecipeCategory.java:88)
01:22:30.056
game
at TRANSFORMER/jei@15.10.0.35/mezz.jei.library.plugins.jei.tags.TagInfoRecipeCategory.setRecipe(TagInfoRecipeCategory.java:34)
01:22:30.056
game
at TRANSFORMER/emi@1.1.10+1.20.1+forge/dev.emi.emi.jemi.JemiRecipe.<init>(JemiRecipe.java:56)
01:22:30.056
game
at TRANSFORMER/emi@1.1.10+1.20.1+forge/dev.emi.emi.jemi.JemiPlugin.register(JemiPlugin.java:262)
01:22:30.056
game
at TRANSFORMER/emi@1.1.10+1.20.1+forge/dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:185)
01:22:30.056
game
at java.base/java.lang.Thread.run(Thread.java:833)
```

jei-1.20.1-forge-15.10.0.35
emi-1.1.10+1.20.1+forge

**Comment by ghost** [comment]
Im having the same porblema

**Comment by emilyploszaj** [comment]
This should be resolved with JEMI improvements in 1.1.11

**Comment by tajemniktv** [comment]
Hi @emilyploszaj, I'm worried that the improvments didn't fix everything... Here's the full log of what I'm getting: 
https://mclo.gs/fHsleIr

But basically a lot of this:
```
[07:58:52] [Thread-48/INFO]: [LoggerPrintStream#log] [STDERR]: java.lang.AbstractMethodError: Receiver class dev.emi.emi.jemi.impl.JemiRecipeSlotBuilder does not define or inherit an implementation of the resolved method 'mezz.jei.api.gui.builder.IIngredientAcceptor addTypedIngredients(java.util.List)' of interface mezz.jei.api.gui.builder.IRecipeSlotBuilder.
[07:58:52] [Thread-48/INFO]: [LoggerPrintStream#log] [STDERR]: 	at mezz.jei.library.plugins.jei.tags.TagInfoRecipeCategory.setRecipe(TagInfoRecipeCategory.java:92)
[07:58:52] [Thread-48/INFO]: [LoggerPrintStream#log] [STDERR]: 	at mezz.jei.library.plugins.jei.tags.TagInfoRecipeCategory.setRecipe(TagInfoRecipeCategory.java:35)
[07:58:52] [Thread-48/INFO]: [LoggerPrintStream#log] [STDERR]: 	at dev.emi.emi.jemi.JemiRecipe.<init>(JemiRecipe.java:55)
[07:58:52] [Thread-48/INFO]: [LoggerPrintStream#log] [STDERR]: 	at dev.emi.emi.jemi.JemiPlugin.register(JemiPlugin.java:263)
[07:58:52] [Thread-48/INFO]: [LoggerPrintStream#log] [STDERR]: 	at dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:185)
[07:58:52] [Thread-48/INFO]: [LoggerPrintStream#log] [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:1570)
```
