### ISSUE TITLE
item texture does not render correctly in the search viewer causing item and recipe viewer errors

### ISSUE THREAD

**Issue by hoenoch** [emilyploszaj/emi#686]
For some reason only using jei can show the correct recipe and slashblade item display of mod SlashBlade:Resharped and it addon SlashBladeJapaneseAddonPack .But emi and emi+jei can't show it correct.

only jei
![2024-09-05_02 39 40](https://github.com/user-attachments/assets/2202c4e7-fb5b-4619-9c1c-11c05924bdce)

only emi
![2024-09-05_02 46 07](https://github.com/user-attachments/assets/6699ec95-a7ad-4dc2-bbd9-9f7757025100)

jei+emi
![2024-09-05_02 35 28](https://github.com/user-attachments/assets/3f5ab739-2d7a-408c-bf8a-dee1c9f50438)

jei recipe
![2024-09-05_03 20 37](https://github.com/user-attachments/assets/5d96575e-6dd8-4274-85fb-d8dbdf4605d6)

emi & jei+emi recipe(both have same problem)
![2024-09-05_03 04 30](https://github.com/user-attachments/assets/e021eaab-5313-4f32-a947-cd38fd8146cb)

mod use
SlashBladeResharped-1.20.1-1.0.1     https://modrinth.com/mod/slashblade-resharped/version/1.0.1
SJAP_Resharpened-1.20.1-1.0.3         https://modrinth.com/mod/sjap/version/1.0.3
emi-1.1.12+1.20.1+forge                   https://modrinth.com/mod/emi/version/1.1.12+1.20.1+forge
jei-1.20.1-forge-15.16.2.73                 https://modrinth.com/mod/jei/version/ysu7j84o
forge loader 47.3.6

PS: this problem look like has been talk about at SlashBlade Resharped github but the respon is there's nothing they can do about this at the moment. https://github.com/0999312/SlashBlade_Resharped/issues/13

**Comment by emilyploszaj** [comment]
This is related to subtype detection and should be resolved in 1.1.13

**Comment by liangmoe** [comment]
issue still persist in 1.1.13, latest.log: https://mclo.gs/jfa0XUw
![2024-09-09_05 45 56](https://github.com/user-attachments/assets/d863508a-4ffb-4aff-ae83-22760a694897)

**Comment by emilyploszaj** [comment]
Oh I see what you mean. This is caused by the mod having very peculiar rendering, you can probably resolve it by turning the batched renderer off

**Comment by hoenoch** [comment]
sorry but even after turning off the batched renderer the issue still persist

![image](https://github.com/user-attachments/assets/29d9be88-fd4e-40e2-be3b-321ed54d9214)

emi+jei         log:https://mclo.gs/qfNv2l0
![2024-09-09_19 41 31](https://github.com/user-attachments/assets/33f303df-d261-4874-8d6c-5c430e7c42ed)

only emi  log:https://mclo.gs/tCCtX7l
![2024-09-09_19 49 37](https://github.com/user-attachments/assets/cac696d1-bdf6-4f5a-8d9c-4de0733c0a8b)
